export const ErrorMessages = {
    YEAR_REQUIRED: 'YEAR_REQUIRED',
    INVALID_YEAR_FORMAT: 'INVALID_YEAR_FORMAT',
    INVALID_PAGE_NUMBER: 'INVALID_PAGE_NUMBER',
    INVALID_MOVIE_ID: 'INVALID_MOVIE_ID',
    API_RESPONSE_INVALID: 'API_RESPONSE_INVALID',
    MOVIE_FETCH_FAILED: 'MOVIE_FETCH_FAILED',
    CREDITS_FETCH_FAILED: 'CREDITS_FETCH_FAILED',
    MOVIE_ID_REQUIRED: 'MOVIE_ID_REQUIRED'
  } as const;
  
  export type ErrorType = typeof ErrorMessages[keyof typeof ErrorMessages];